feat: 카카오 로컬 API 호출 + DB에 가맹점 데이터 저장
mju-likelion/hackathon-team2-server pull request #3
Opened 2023-07-31 07:01 UTC by hy5sun

2023-08-02 18:26 UTC, hy5sun commented
1. csv 파일 속 잘못된 주소값을 가진 데이터가 있었습니다. 따라서 아래와 같이 변경했습니다.
   - 기존 : csv 파일 속 도로명 주소와 지번 주소를 그대로 DB에 저장 
   -> 현재 : `키워드로 장소 검색하기 API` 에서 불러와 저장
   - 기존 : csv 파일 속 지번 주소를 통해 `장소 검색하기 API` 호출 후, 위도, 경도 값을 불러와 DB에 저장 
   ->현재 : `키워드로 장소 검색하기 API` 에서 불러와 저장

2. 지번 주소 중 `시` 와 `구` 에 해당하는 주소는 제외시켜 저장했습니다.

3. 지도 상에 가게가 존재한다면 `위도`, `경도`, `도로명 주소`, `지번 주소` 값은 필수적으로 있을 것이므로, 이 값들이 없을 경우 폐점으로 판단하여 DB에 저장하지 않도록 했습니다.

2023-08-03 10:39 UTC, zelkovaria reviewed
섭짱이 말해주셨습니당

2023-08-03 10:39 UTC, zelkovaria commented on prisma/schema.prisma
> +  store           Store?
optional 이 아니라 required 이 와야 함

2023-08-03 10:39 UTC, zelkovaria commented on src/kakao/kakao.service.ts
> +      return;
catch 를 throw 하지 않고 그냥 return 하는건 try catch 문을 안쓰는거랑 똑같습니다. 뭐라도 처리해주세요 (근데 급하면 우선순위가 낮긴 합니다)

2023-08-03 10:39 UTC, zelkovaria commented on src/kakao/kakao.service.ts
> +    const storeInf = {
보통 information 은 줄여서 info 라고 해요. inf 라고 하면 infinite 랑 헷갈릴 수 있어서요!

2023-08-03 10:39 UTC, zelkovaria commented on src/kakao/kakao.service.ts
> +    }
위의 주석과 밑의 코드가 맞지 않아요. 위의 주석은 if else 문이여야 하는 녀석이고, try catch 는 에러가 throw 되거나 promise 가 reject 되는것을 잡는 용 구문입니다

2023-08-03 10:39 UTC, zelkovaria commented on src/store/store.service.ts
> +import { KakaoService } from 'src/kakao/kakao.service';
relative path 를 사용해보도록 해보시죠!

2023-08-03 10:39 UTC, zelkovaria commented on src/store/store.service.ts
> +    }
javaScript 는 프로그래밍 언어 치고 함수형이라, 신기할 정도로 for 문을 사용하지 않습니다. forEach문이나 map으로 바꿔보세요

2023-08-03 10:39 UTC, zelkovaria commented on src/store/store.service.ts
> +    const absoluteFilePath = process.env.CSV_FILE_PATH;
csv 파일을 반드시 서버에 넣어야 하는 방법은 좋지 않습니다. 배포 이후에 사용할 수 없는 기능이 되니까요 (배포 컴에는 csv 를 구역구역 넣을 수 없으므로) 이건 사용자로부터 csv 를 업로드 받도록 바꾸시는게 확장성에 좋아요

2023-08-03 10:40 UTC, zelkovaria reviewed
굿

2023-08-03 10:40 UTC, zelkovaria reviewed
try catch -> if else

2023-08-03 10:40 UTC, hy5sun commented on prisma/schema.prisma
> +  store           Store?
[공식문서](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-one-relations#required-and-optional-1-1-relation-fields)보면 1:1 관계에서는 @relation이 없는 쪽에는 optional 이어야 한다고 합니다!

2023-08-03 10:44 UTC, hy5sun commented on src/kakao/kakao.service.ts
> +      return;
이 부분도 전화번호 불러오는 코드 처럼 `위도, 경도, 도로명주소, 지번주소가 없으면 아무 값 넘겨주지 말라`는 의도를 가지고 짠 코드기 때문에 if else문으로 수정하겠습니다!

2023-08-03 10:45 UTC, hy5sun commented on src/kakao/kakao.service.ts
> +    const storeInf = {
수정하겠습니다!

2023-08-03 10:46 UTC, hy5sun commented on src/kakao/kakao.service.ts
> +    }
phoneNumber 값이 불러와지지 않으면 error가 발생해서 이와 같이 작성했던건데, 리뷰해주신대로 if else문을 사용한 코드가 더 적합한 것 같습니다. 수정하겠습니다~!

2023-08-03 10:47 UTC, hy5sun commented on src/store/store.service.ts
> +import { KakaoService } from 'src/kakao/kakao.service';
relative path 를 사용하는 이유가 단순히 경로를 깔끔하게 하기 위해서인가요?

2023-08-03 10:48 UTC, hy5sun commented on src/store/store.service.ts
> +    }
네 수정해보겠습니다!

2023-08-03 10:48 UTC, hy5sun commented on src/store/store.service.ts
> +    const absoluteFilePath = process.env.CSV_FILE_PATH;
파라미터로 파일을 받아야 한다는 걸로 이해했는데 맞을까요?

2023-08-03 13:28 UTC, ndaemy requested changes
화이팅! 💪

2023-08-03 13:28 UTC, ndaemy commented on prisma/schema.prisma
> +  store           Store?
허.. 그러네요 prisma 가 아쉬운 부분이 하나 생겼군

2023-08-03 13:28 UTC, ndaemy commented on src/kakao/kakao.service.ts
> +    const response = await axios.get(url, {
이거 axios 에 generic 달아주시죠!

2023-08-03 13:28 UTC, ndaemy commented on src/kakao/kakao.service.ts
> +    const datas = response.data.documents[0];
https://bskyvision.com/entry/data%EC%97%90-s-%EB%B6%99%EC%9D%B4%EB%A9%B4-%EC%95%88-%EB%90%A9%EB%8B%88%EB%8B%A4

^^

2023-08-03 13:28 UTC, ndaemy commented on src/kakao/kakao.service.ts
> +      }
이거 리팩토링 요망이여

2023-08-03 13:28 UTC, ndaemy commented on src/store/store.service.ts
> +import { KakaoService } from 'src/kakao/kakao.service';
넹 맞아여
물론 그 말 안에 쓰는 사람의 가독성 읽는 사람의 가독성 등등이 포함되는 말이지만여

2023-08-03 13:28 UTC, ndaemy commented on prisma/schema.prisma
> +  name      String
name 은 unique 해야 하지 않나요?

2023-08-03 13:28 UTC, ndaemy commented on src/store/store.service.ts
> +      const store = await this.prismaService.category.findFirst({
위의 코드리뷰 (name 은 unique 해야 한다) 랑 연결되는건데, 만약 name 이 unique 하다면 findFirst() 보다 findUnique() 가 더 낫습니다

2023-08-03 13:28 UTC, ndaemy commented on src/store/store.service.ts
> +    const absoluteFilePath = process.env.CSV_FILE_PATH;
넹 맞아여 upload File 같은 방식을 이야기한거였어요.
그러면 추후에 만약 어드민 같은걸 만든다고 해도 재활용이 가능하니까요.

2023-08-03 15:26 UTC, hy5sun commented
csv 파일 업로드 API는 추후에 만들기로 했습니다.

2023-08-03 16:27 UTC, hy5sun commented on src/kakao/kakao.service.ts
> +    const datas = response.data.documents[0];
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
수정할게요 ...

2023-08-04 06:43 UTC, hy5sun commented on src/store/store.service.ts
> +    const absoluteFilePath = process.env.CSV_FILE_PATH;
이 부분은 추후에 만들도록 하겠습니다...!

2023-08-04 08:21 UTC, hy5sun commented
csv 파일을 직접 올리게 하는 건 추후에 추가하도록 하겠습니다.
지금 당장 필요한 기능은 아니라 후순위로 미뤄야 할 것 같아요

2023-08-04 13:04 UTC, merged