feat: 지도 메인페이지 api 구현
mju-likelion/hackathon-team2-server pull request #6
Opened 2023-08-05 01:44 UTC by hy5sun

지도 메인페이지 API 구현 했습니다!

- 사용자의 위치 좌표 (위도, 경도) 와 radius (반경) 값을 params로 받아옴
- StoreLocation 테이블에 저장된 데이터 중 반경 내에 속한 좌푯값을 필터링함
- 필터링된 위치 데이터를 기반으로 Store 테이블과 Category 테이블 속 데이터를 가져옴

2023-08-06 06:58 UTC, hy5sun commented
- 사용자의 현재 위치 좌표와 반경 거리를 params로 받지 않고, 지도의 꼭짓점에 해당하는 4곳의 위도/경도를 params로 받는 걸로 수정
     -> 위도/경도의 최대, 최솟값 사이의 범위에 있는 가맹점 정보를 반환

- decimal.js 패키지를 사용하여 실수 비교연산을 수행하도록 함
- API 주솟값 수정 : `/map` -> `/store`

2023-08-06 07:15 UTC, ndaemy requested changes

2023-08-06 07:15 UTC, ndaemy commented on src/map/map.controller.ts
> +import { Controller, Get, Param, Query } from '@nestjs/common';
얜 갑자기 왜 추가된거에요..?

2023-08-06 07:15 UTC, ndaemy commented on src/store/store.service.ts
> +interface storeData {
interface 는 PascalCase로 쓰셔야 합니다!

2023-08-06 16:17 UTC, hy5sun commented on src/map/map.controller.ts
> +import { Controller, Get, Param, Query } from '@nestjs/common';
ㅎ....... 옮기고 옮기다가 실수로 삭제 안 했네요,,

2023-08-06 16:17 UTC, hy5sun commented on src/store/store.service.ts
> +interface storeData {
헉 네 수정할게요!

2023-08-06 16:52 UTC, hy5sun commented
- API 주소 수정 : `/store` -> `/stores`
- StoreLocation -> Location으로 테이블명 수정
- latitude 와 longitude 타입 String -> Decimal 로 수정 + index 추가
- 데이터 가져오면서 필터링 하도록 수정

2023-08-09 19:19 UTC, ndaemy approved these changes
수고하셔쓰영

2023-08-09 22:52 UTC, merged